apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2  # Number of instances
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: ashish2705/maven-hello-world:latest  # Matches the image name in Jenkins
        ports:
        - containerPort: 8080  # App’s exposed port in the container
