apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Port your container is exposing
  type: LoadBalancer  # Use NodePort for local testing, LoadBalancer for cloud
